name: css_upgrade_pr

on:
  schedule:
    - cron: "0 6 * * MON-FRI"

jobs:
  create_pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.8
          bundler-cache: true
          cache-version: 2
      - name: Replace abukuma css
        run: |
          curl -o lib/assets/stylesheets/gifteeabukumacss/rails/style.css https://cdn.jsdelivr.net/npm/@giftee/abukuma-css@latest/dist/style.css
          bundle exec rubocop -A

          CURRENT_DATETIME=$(date +'%Y%m%d%H%M')
          BRANCH_NAME="feature/css_upgrade/graphql_diff_$CURRENT_DATETIME"

          git config user.name github-actions
          git config user.email github-actions@github.com

          git switch -c $BRANCH_NAME
          git add .
          git commit -m "[自動]AbukumaCSSの差分吸収_$CURRENT_DATETIME"
          git push -u origin $BRANCH_NAME
          gh pr create --base $BASE_BRANCH --title "[自動]AbukumaCSSの差分吸収" --body "[自動]AbukumaCSSの差分吸収" --head $(git branch --show-current)
          echo "url=$(gh pr view --json url $BRANCH_NAME --jq .url)" >> $GITHUB_OUTPUT
