name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout with push
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true
          cache-version: 2
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop
